#spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management_db
spring.datasource.username=postgres
spring.datasource.password=123

#It saves you from writing manual SQL CREATE TABLE or ALTER TABLE scripts during development.
#spring.jpa.hibernate.ddl-auto=update

#This below line prints every SQL query that Hibernate generates into your console/terminal.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Even though SQL is a standard, different databases (PostgreSQL, MySQL, Oracle) have slight variations in syntax.
# The Dialect ensures Hibernate generates the specific syntax that PostgreSQL understands.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
